### ISSUE TITLE
Minor issues and enhancements for theme (to be broken into individual issues)

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/bambusa-theme#2]
### In priority order
- [x] Spacing after UL/OL doesn't match space after P's, spacing before UL/OL could be reduced. I think you might need to add.... `ol, ul { margin-bottom: 1.5rem; }` and `p + ol, p+ ul { margin-top: -0.5rem }` https://github.com/silverstripe/bambusa-theme/pull/34
- [x] language switcher is not aligned to the right of the header area
- [x] Language switcher selected text colour is not white
![Pasted_Image_1_08_19__10_50_AM.png](https://images.zenhubusercontent.com/574b650dbf93871ccd9bc88f/87c98d28-3e9b-41f8-8a51-2eed5c8b8152)
- [x] Remove underlines on links if they are remaining blue `.main a {
     text-decoration: none; }`
- [x] Reduce spacing of .carousel-item to `padding-top: 5rem, padding-bottom 5rem`, and move .carousel-controls-wrapper down slightly so `bottom: 30px` it currently looks bad when in use with a single image, e.g. internal landing pages
- [x] Breadcrumb doesn't pass contrast tests, I think it was previously white?
![Pasted_Image_12_08_19__11_51_AM.png](https://images.zenhubusercontent.com/574b650dbf93871ccd9bc88f/d6e2d526-5a3b-4e43-806e-511f9e4fe28f)
- [x] Style **preformatted** text with, No borders, border-radius:1rem, background-color:$gray-200, padding:0.5rem 1rem;

- [x] Add additional space before the footer—the last block is quite tight to the footer
- [ ] ~~Text gets cropped at certain screen sizes~~ moved to https://github.com/silverstripe/bambusa-theme/issues/44
![Pasted_Image_12_08_19__11_38_AM.png](https://images.zenhubusercontent.com/574b650dbf93871ccd9bc88f/4a93b9f6-d49b-45d4-ab70-2aef086a6218)
- [x] ~~Uncaptioned centred images doesn't have a `margin-bottom: 18px;` in TinyMCE... add `:not(.captionImage) .captionImage.center-block;` to .captionImage.center styles~~ (fixed by https://github.com/silverstripe/cwp-starter-theme/pull/159/files)
- [x] Drop menu hover bg not very visible change to $gray200
- [ ] ~~All button sizes do not use the rounded corner style that normal buttons do~~ opened seperate issue https://github.com/silverstripe/bambusa-theme/issues/43
- [x] Carousels don't look good on inner content pages, can we have a class on the homepage so we can have margin beneath the carousel but other pages not?
![Pasted_Image_2_08_19__4_17_PM.png](https://images.zenhubusercontent.com/574b650dbf93871ccd9bc88f/1b721a63-55ad-49c1-9d2c-912f43da204f)

## Done
- [ ] ~~Link colour is not changeable in colour picker~~ (raised as separate issue https://app.zenhub.com/workspaces/open-sorcerers-52b2f493f0808b12020000f8/issues/silverstripe/silverstripe-admin/919)
- [ ] ~~CMS is inheriting styles from the Debug bar, noticeable with block header colour (might be the issue with site tree font being too big).~~ Will be removed
- [x] Mobile hamburger does not appear
- [x] Mobile menu needs left and right padding
- [x] Navigation dropdown arrow is off centre 
- [x] SS logo has wrong link, please update to go to silverstripe.com (See PR)
- [x] Content blocks don't show any content (only header is shown)
- [x] Banner block has no content coming out
- [x] ~The page type "Page" returns a server error. We need this pagetype for broken links report as blocks don't support this feature currently~ Issue: https://app.zenhub.com/workspaces/open-sorcerers-52b2f493f0808b12020000f8/issues/silverstripe/bambusa-installer/35
- [x] Heading sizes are all out, including other like "preformated" (See PR)
- [x] Image alignment not working, not coming into the editor either (See PR)
- [x] Modal for warning about demo, button has bright blue border
- [x] All buttons should use the selected theme colour in the colour picker
- [x] Can't use image centring, editor styles are not reflected in the editor either (See PR)
- [x] Main menu dropdown has gap (See PR)
- [x] ~~Remove gap between navbar and mobile menu~~ required for search area
- [x] Add margin bottom for buttons in mobile view of the carousel
- [x] Ensure that carousel text and Left/right arrows don't overlap on mobile view. Consider reducing left/right arrow buttons 
- [x] Add .lead to the "Format" dropdown
- [ ] moved to https://app.zenhub.com/workspaces/open-sorcerers-52b2f493f0808b12020000f8/issues/silverstripe/silverstripe-admin/920
To be ported over once functionality is added: ~~Bring over the accessibility improvements currently going into Watea to Bambusa (select ones which are most relevant) 
https://github.com/silverstripe/cwp-watea-theme/pull/96 (Language selector)
https://github.com/silverstripe/cwp-watea-theme/pull/97 (Search) 
https://github.com/silverstripe/cwp-watea-theme/pull/92 (Indicators)
https://github.com/silverstripe/cwp-watea-theme/pull/99 (Colour picker work)~~
- [x] Created seperate issue... ~~Banner block design: solid colour in behind text with white text. At large sizes, content can sit on the left with the image on right, smaller sizes image on top and text below. Design https://projects.invisionapp.com/d/main?origin=v7#/console/15471951/331473257/preview~~
- [x] Buttons to go rounded (padding left and right should be 1rem, border radius 2 rem)
- [x] RAISED ELSEWARE  ~~Carousel: text size smaller, no mask, remove lg buttons, pager to have .8 bg coloraturas and rounded~~
- [x] The Bambusa theme requires a favicon which represents the theme, requires design. At a minimum, it should use the SilverStripe favicon but I have a preference for it to have its own.

# Pull Requests

- [X] https://github.com/silverstripe/bambusa-theme/pull/34
- [x] https://github.com/silverstripe/bambusa-theme/pull/37

**Comment by newleeland** [comment]
It might be good have a set apart time where someone from PUX could sit down with a dev for an 1hr and churn this out.

**Comment by clarkepaul** [comment]
@newleeland bigger issues need to be feedback into current development issues otherwise we will work with @sachajudd to go through some. I've sat with Aaron a few times to get some of these items included already.

**Comment by bergice** [comment]
I've left another pull request resolving all the checkboxes from the top up until `Add additional space before the footer—the last block is quite tight to the footer`. Didn't have time for the rest.

https://github.com/silverstripe/bambusa-theme/pull/37

**Comment by clarkepaul** [comment]
@chillu some of these PR's haven't made their way to Prod yet but they have all either been done or opened as separate issues for going forward. You might want to close this one-off if all the PR's have made their way into UAT.

**Comment by chillu** [comment]
@clarkepaul All on UAT now. Once you're happy with it I'll put it on prod

**Comment by chillu** [comment]
That's on prod now.
