### ISSUE TITLE
Bannerblock theme issues

### ISSUE THREAD

**Issue by chillu** [silverstripe/bambusa-theme#28]
Moved from https://github.com/silverstripe/silverstripe-elemental-bannerblock/issues/28 /cc @clarkepaul 

- [x] Remove the enlarging of the image on hover completely, in its place add an additional line of CSS for when hovered and there is a working link `transform: translateY(-2px);` 
- [x] Only show the drop shadow when hovering the block if it is linkable
- [x] Add `transition: transform .3s,box-shadow .3s,` for when it's not hovered to create a smooth transition for when it is hovered.
- [x] Colour contrast of the gradients need to be darker (happy to work through this with a dev).

# Pull requests
 - [x] https://github.com/silverstripe/bambusa-theme/pull/33

**Comment by unclecheese** [comment]
All done. A few notes

* If a banner is linkable, it has no shadow, then when hovered, it gets a shadow and shifts -2px. Is that correct? It looks a bit weird. The shadow is a bit much.

* Used my best judgment for darkening the gradient:

```
      background: linear-gradient(
        64deg,
        desaturate(lighten(adjust-hue($color, -26.4%), 0%), 38%) 0%,
        desaturate(lighten(adjust-hue($color, 0%), 11%), 0%) 100%
      );
```

**Comment by clarkepaul** [comment]
Taken a look over @unclecheese 's shoulder and the transition looks good on hover. We're not 100% on the gradient colours but for now, they will need to do.
