### ISSUE TITLE
Banner text gets cropped if there is too much

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/bambusa-theme#44]
**Issue:** Text gets cropped at certain screen sizes. 

**Recommendation:** The height should be min-height rather than a specified fixed height to accommodate what content is entered (an alternative approach would be to use an ellipsis on the content but I personally don't like this approach with body content).
![image](https://user-images.githubusercontent.com/555033/62984505-97e8f580-be87-11e9-986c-6175c4d0c06f.png)

We need to account for multiple lines for the header, the body text and links (if visible).

# Pull requests
* https://github.com/silverstripe/bambusa-theme/pull/45

**Comment by chillu** [comment]
@clarkepaul This is on UAT now

**Comment by clarkepaul** [comment]
Works great, nice one.
