### ISSUE TITLE
Banner block requires design

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/bambusa-theme#9]
## ACs

The Banner block comes with the following functionality for content authors:
- I can add an image (if no image is added the gradient background takes the entire space)
- The image is automatically cropped to a suitable aspect ratio for mobile and desktop views
- Any cropping takes the focuspoint module into account
- I can add somebody text, links etc.
- I can add a title
- I can add an internal site link with custom link text (if it is added the link appears below the body text), and the entire block acts as the link (not just the link text). 
- Takes colour picker choices into consideration
- Prevents authors from breaking design in horrible ways with too much content

<img width="403" alt="Pasted_Image_11_07_19__1_07_PM" src="https://user-images.githubusercontent.com/555033/61015291-077a4980-a3df-11e9-8963-8b7d1c932e68.png">

Full page mockup:
https://projects.invisionapp.com/d/main?origin=v7#/console/15471951/331473257/preview

**Design points desktop view**
- Panel:
width: 100%;
border-radius: 8px; (or large radius used in variables?)
box-shadow: 0 6px 8px 0 rgba(0,0,0,0.15), 0 10px 40px 0 rgba(0,0,0,0.20);
padding: 40px 30px;

- Image:
width: 50% on right side

- Solid block of colour in behind text:
background-image: linear-gradient(64deg, #C62741 0%, #F48448 100%);
border-radius: 8px 0 0 8px;
Width: 50%;
color: #fff;

- Links to be white with an underline, except for the link which has the arrow (only show if the link is added via the CMS).

Paul to supply the SVG arrow.

**Design points mobile view**
- Image 100% width and sits on top of content panel 
- Gradiant panel: border-radius: 0 0 8px 8px; sits underneath image with auto height

# Pulls request
* [x] https://github.com/silverstripe/bambusa-theme/pull/24
* [ ] ~~https://github.com/silverstripe/bambusa-installer/pull/46~~
* [x] https://github.com/silverstripe/silverstripe-theme-colorpicker/pull/2
* [x] https://github.com/silverstripe/bambusa-installer/pull/48

**Comment by clarkepaul** [comment]
@chillu banner design, I will supply the arrow SVG when someone picks it up.

**Comment by chillu** [comment]
I've asked CCs for their feedback:

> Need some feedback on banner block additions which Paul is pushing for on Bambusa: https://github.com/silverstripe/bambusa-theme/issues/9. The banner block is currently part of `silverstripe/elemental-bannerblock`, which is a supported module. I think those features (upload image for side-by-side display) are reasonable, and should be available in Watea as well.  Otherwise, it appears that the designs can be fulfilled with the existing model (assuming the headline is part of the rich text content, and not a separate field. https://github.com/silverstripe/silverstripe-elemental-bannerblock/blob/master/src/Block/BannerBlock.php

> If we’re creating an issue to backport this support to Watea (hopefully with @sacha across it), are you OK with adding this as a module feature, rather than an extension that’s specific to bambusa installer (and hence not available to actual teams using this in actual bespoke projects)?

**Comment by maxime-rainville** [comment]
@clarkepaul 

> Takes colour picker choices into consideration

Didn't we have a discussion at our backlog planning session that we wouldn't do this? If not, I'll need some clarification about how to approach generating the gradient for this thing.

Also, I recall us talking about making the entire banner click-able, which would negate the need for call to action.

**Comment by chillu** [comment]
> Didn't we have a discussion at our backlog planning session that we wouldn't do this? 

Hmm, damn can't remember. But I'd flag that it'll look very out of place in some of the colour combinations, and banners are used all over the place in sample content. I think we *need* to account for this in the colour pickers. Hopefully by reusing an existing color, e.g. the "accent" colour?

> Also, I recall us talking about making the entire banner click-able, which would negate the need for call to action.

I think we still need the "read more", and it should still be a link - for accessibility reasons alone. If we make the whole banner clickable, please ensure it can receive visible keyboard focus.

**Comment by clarkepaul** [comment]
**Background colour**, I think we said we would try to use the theme colour and work out if a secondary colour could be used, the theme picker is in now so I will take a look. 

**Link text** is still good to have to make it appear linkable but I think you only need the actual link to be around the whole thing.

**Comment by maxime-rainville** [comment]
@clarkepaul Got the basic look and feel going. It's just down to cleaning up the details: https://youtu.be/PlcChzXG96E

I added a mouse over effect. The image is actually a background and it uses background-position and `background-size: cover` to make sure the focus point is always shown.

Things left to do: 
* wrap the entire thing in an anchor
* make sure it works in IE
* tweak typeface
* add the icon next to the call to action
* make sure the text gets cut off when needed
* try to compute a sensible gradient off the custom colours

**Comment by clarkepaul** [comment]
@maxime-rainville Very cool, love that it works with focus point (browny points right there).

- I didn't see any cursor change when hovering or maybe the link wasn't there? the cursor change should be on the entire banner block, and if there is no link there shouldn't be any image enlargement fanciness.
- Can you reduce the amount of image scaling, looks a bit too distracting
- I'll send you the arrow SVG for the link

Keen to see the gradients to check contrast when possible (maybe on UAT).

**Comment by maxime-rainville** [comment]
PRs are almost ready for review ... just missing the svg for the call to action.

The entire banner is wrap in A tag now, so it's all clickable. To get this to work I had to change a lot of the DIVs to span, because some browsers didn't have like having block elements inside an A tag. I added appropriate `role` attributes on various elements.

The text gets trunctated after 30 words ... the text-overflow css attributes only works if your set your content not to wrap, which couldn't work in our use case.

I've also added the ability to pick a custom colours for the gradients. The actual start and end colours get computed based on what you selected.

I reduce the zoom -in effect on mouse over from 20% to 10% as requested.

Tested it in FireFox, Chrome, IE 10 and IE 11.

**Comment by clarkepaul** [comment]
> I had to change a lot of the DIVs to span, because some browsers didn't have like having block elements inside an A tag.

I thought that was only the case for older browsers, pretty sure div's are fine nowadays with HTML5—could be wrong though. 

Keen to see it in action on UAT :), choosing colours sounds pretty fancy.

**Comment by maxime-rainville** [comment]
I thought so as well, but Firefox was throwing a fit and trying to correct the DOM.

**Comment by maxime-rainville** [comment]
Icon has been added ... ready for PR.

**Comment by chillu** [comment]
@clarkepaul @newleeland This is on UAT now if you want to check the design implementation.

**Comment by chillu** [comment]
@clarkepaul Is this really the default color combo we want to go for? The blue vs. orange looks a bit of a stark contrast - although that's just an opinion of course.

![image](https://user-images.githubusercontent.com/111025/62178579-afab7e80-b39d-11e9-97e1-7a13dcf25766.png)

**Comment by clarkepaul** [comment]
These are the closest colours to the ones on the banners so it was designed to have them included. From the colours which are in the colour picker, I think these work the best and give it some vibrancy. 

We are going to have to adjust the way the colours are outputted because they don't pass colour contrast testing in most cases based on the way the gradients have been created (the colours I provided are darker—even more of a "stark contrast" :P )

@maxime-rainville 
- I couldn't get the linking to work at all 
- The enlarging of the image should only be there is links are included
- Colour contrast of the gradients need to be darker (happy to work through this with a dev)

**Comment by clarkepaul** [comment]
Moved the remaining issues to a new issue as requested https://github.com/silverstripe/silverstripe-admin/issues/918
